### ISSUE TITLE
potential problem in code

### ISSUE THREAD

**Issue by xweiyuan** [NVlabs/few-shot-vid2vid#11]
I think `t_step = np.random.randint(max_t_step) + 1   `  in _./data/base_dataset.py_ would throw an error when `cur_seq_len` equals to 1.

Maybe an if-clause like `if max_t_step==0: t_step=1` should be added to avoid crash while training?

**Comment by tcwang0509** [comment]
```cur_seq_len``` shouldn't really be 1, which means the video only consists of one frame. But I guess there's no hurt checking that too. Thanks for the info!

**Comment by xweiyuan** [comment]
Thanks for your reply and great work.
Besides, the code will throw out dimension mismatching error while fetching data as bellow:

'invalid argument 0: Sizes of tensors must match except in dimension 0. Got 4 and 3 in dimension 1 at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/TH/generic/THTensor.cpp:689'

Maybe it is better to filter out the video sequences which is too short, like less than the `seq_len_max `?
