### ISSUE TITLE
Pretrained network G has fewer layers

### ISSUE THREAD

**Issue by shikhar-scs** [NVlabs/few-shot-vid2vid#15]
I was running the model using a sample image and sequence after training it. 
I get the following error. Help!

```
python test.py --name face --dataset_mode fewshot_face --adaptive_spade --warp_ref --spade_combine --seq_path input_data/sequence.mp4 --ref_img_path example.png
```

```error
CustomDatasetDataLoader
dataset [FaceDataset] was created
---------- Networks initialized -------------
---------- Optimizers initialized -------------
Pretrained network G has fewer layers; The following are not initialized:
['flow_network_temp.conv_flow', 'flow_network_temp.conv_w', 'flow_network_temp.down_flow', 'flow_network_temp.res_flow', 'flow_network_temp.up_flow']
model [Vid2VidModel] was created
```

**Comment by chenwq-bjtu** [comment]
I have the same problem, but it can pass.
occurs error when enumrate dataset:

Traceback (most recent call last):
  File "test.py", line 36, in <module>
    for i, data in enumerate(dataset):
  File "/home/ml/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/ml/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/ml/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: function takes exactly 5 arguments (1 given)

**Comment by deepfakes-facejap** [comment]
@shikhar-scs  Your training is still the first stage.
By default, after 100 epochs(single) and 100 epochs(double),  flow_network will be generated on vid2vid step.
