### ISSUE TITLE
Iterations for benchmark?

### ISSUE THREAD

**Issue by pythagoras000** [NVlabs/few-shot-vid2vid#16]
I've reviewed the paper and readme but can't find any reference to how many iterations were used to achieve the results as displayed on the gifs of this repo. 
I can see in the paper that training was conducted using an NVIDIA DGX-1 machine with 8 32GB V100 GPUs, but how many iterations were done and how long did it took to complete the training?

**Comment by k4rth33k** [comment]
I think the total iterations need to be 200 or more with 100 iterations per each frame.

**Comment by pythagoras000** [comment]
@k4rth33k thanks for your reply, can you let me know where in the paper or repo they reference this? 
Also, how much time do you think this would take using NVIDIA DGX-1 machine with 8 32GB V100 GPUs?

**Comment by k4rth33k** [comment]
@ssaleth You can find it in the command to start the training for poses in the Readme.md file:

`python train.py --name pose --dataset_mode fewshot_pose --adaptive_spade --warp_ref --spade_combine --remove_face_labels --add_face_D --niter_single 100 --niter 200 --batchSize 2
`
--niter is set to 200. The actual total iterations might be more as it is not specified anywhere. My estimate might be wrong but I think it'll take DGX-1 less than 8 hours for the above configuration.

**Comment by pythagoras000** [comment]
Thanks a lot @k4rth33k ! Just to confirm, the above configuration achieves the best result possible right? So do you think I would be able to replicate the same results as shown in this repo with 8 hours of training on a [AWS p3.16xlarge](https://aws.amazon.com/blogs/aws/new-amazon-ec2-instances-with-up-to-8-nvidia-tesla-v100-gpus-p3/)?

**Comment by k4rth33k** [comment]
I'm not sure whether that config is the one that can exactly replicate the GIFs in the repo but I'm sure that it will give you a more than decent result.

**Comment by pythagoras000** [comment]
Got it, thanks @k4rth33k !
