### ISSUE TITLE
Add parameter '--tf_log' error

### ISSUE THREAD

**Issue by jackweiwang** [NVlabs/few-shot-vid2vid#20]
Traceback (most recent call last):
  File "train.py", line 69, in <module>
    train()
  File "train.py", line 58, in train
    if trainer.end_of_iter(loss_dict, generated + data_list + data_ref_list, model):
  File "/home/ww/myGit/few-shot-vid2vid/models/trainer.py", line 58, in end_of_iter
    self.visualizer.display_current_results(visuals, epoch, total_steps)
  File "/home/ww/myGit/few-shot-vid2vid/util/visualizer.py", line 98, in display_current_results
    if len(image_numpy.shape) >= 4:
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by AaronWong** [comment]
add
`if image_numpy is None: continue`
below  [visualizer.py](https://github.com/NVlabs/few-shot-vid2vid/blob/master/util/visualizer.py#L91)
`for label, image_numpy in visuals.items():`
```python
        if self.tf_log: # show images in tensorboard output
            img_summaries = []
            for label, image_numpy in visuals.items():
                if image_numpy is None: continue
                # Write the image to a string
```

**Comment by jackweiwang** [comment]
> add
> `if image_numpy is None: continue`
> below [visualizer.py](https://github.com/NVlabs/few-shot-vid2vid/blob/master/util/visualizer.py#L91)
> `for label, image_numpy in visuals.items():`
> 
> ```python
>         if self.tf_log: # show images in tensorboard output
>             img_summaries = []
>             for label, image_numpy in visuals.items():
>                 if image_numpy is None: continue
>                 # Write the image to a string
> ```

thanks
