### ISSUE TITLE
How to train on multi-nodes?

### ISSUE THREAD

**Issue by howardgriffin** [NVlabs/few-shot-vid2vid#25]
I noticed the parameter 'distributed' in base_options.py. Howevery, when I add this parameter to train on multiple nodes and multiple GPUs, the following error ocurs. Could anyone tell me how to solve it?
![无标题](https://user-images.githubusercontent.com/23454942/71883826-29783d00-3172-11ea-878e-e938608d7025.png)

**Comment by BaldrLector** [comment]
@howardgriffin
it seems you need to set RANK in your environ variable, see https://github.com/seba-1511/dist_tuto.pth, make sure NCCL or MPI is installed.

and horovod https://github.com/horovod/horovod may be easier than DDP for beginner
