### ISSUE TITLE
TypeError: vis_print() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by surendra1472** [NVlabs/few-shot-vid2vid#32]
I tried running pose example provided and when trying to predict getting the following error

CustomDatasetDataLoader
dataset [PoseDataset] was created
---------- Networks initialized -------------
---------- Optimizers initialized -------------
Pretrained network G has fewer layers; The following are not initialized:
['flow_network_temp.conv_flow', 'flow_network_temp.conv_w', 'flow_network_temp.down_flow', 'flow_network_temp.res_flow', 'flow_network_temp.up_flow', 'img_prev_embedding.conv_first', 'img_prev_embedding.down_0', 'img_prev_embedding.down_1', 'img_prev_embedding.down_2', 'img_prev_embedding.down_3', 'img_prev_embedding.down_4']
model [Vid2VidModel] was created
first image
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    synthesized_image, _, _, _, _, _ = model(data_list)
  File "/home/Vikas/.conda/envs/vid2vid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Vikas/few-shot-vid2vid/models/vid2vid_model.py", line 55, in forward
    return self.inference(tgt_label, ref_labels, ref_images)
  File "/home/Vikas/few-shot-vid2vid/models/vid2vid_model.py", line 188, in inference
    self.finetune(ref_labels, ref_images)
  File "/home/Vikas/few-shot-vid2vid/models/vid2vid_model.py", line 205, in finetune
    params, _ = self.get_train_params(self.netG, train_names)
  File "/home/Vikas/few-shot-vid2vid/models/base_model.py", line 163, in get_train_params
    Visualizer.vis_print(self.opt, 'training layers: ', train_list)
TypeError: vis_print() takes 2 positional arguments but 3 were given

**Comment by surendra1472** [comment]
I found the fix. But do not have access to raise pull request. Please provide.
In the place of https://github.com/NVlabs/few-shot-vid2vid/blob/master/models/base_model.py#L163
just we need to replace like `Visualizer.vis_print(self.opt,  train_list)`

**Comment by tcwang0509** [comment]
Thanks! Fixed in the latest commit.
