### ISSUE TITLE
about pose training details

### ISSUE THREAD

**Issue by CrossLee1** [NVlabs/few-shot-vid2vid#33]
1. how many dancing videos collected for training pose
2. how many frames extracted from each training video
3. is it necessary that each video extract same number of frames

Thanks~

**Comment by tcwang0509** [comment]
We collected about 1000 videos, with varying number of frames. They don't need to be the same.

**Comment by Z863058** [comment]
> We collected about 1000 videos, with varying number of frames. They don't need to be the same.

Great work!
Can I ask What the approximate length of each video for training is? 10 seconds? 1 minutes? or longer?
Thanks a lot!
