### ISSUE TITLE
Have anybody successfully reproduced the  performance as in example videos?

### ISSUE THREAD

**Issue by liyuanhangsc** [NVlabs/few-shot-vid2vid#35]
I tried to train the face model step by step exactly follow the guide, with the default hyper params several times, but all models collapsed with producing bad images after 50 epochs. 
I also tried to adjust some hyper params like lr, batchsize, niter_step,  still failed.
Kindly asking for somebody who have successfully trained a face model share some experience with me . Best regards!

**Comment by tcwang0509** [comment]
Sorry there was a potential bug in the temporal training part that should be fixed in the latest commit. Please pull the latest code and try again.

**Comment by liyuanhangsc** [comment]
> Sorry there was a potential bug in the temporal training part that should be fixed in the latest commit. Please pull the latest code and try again.

Thanks a lot.  I will try to train again.

**Comment by alexcdot** [comment]
@liyuanhangsc How did that go? Did it work?

**Comment by ghost** [comment]
怎么样了

**Comment by tcwang0509** [comment]
This repo is now deprecated. Please refer to the new Imaginaire repo: https://github.com/NVlabs/imaginaire.
