### ISSUE TITLE
Training gets stuck after epoch 50 is complete

### ISSUE THREAD

**Issue by FredMusoro** [NVlabs/few-shot-vid2vid#37]
I've cloned the latest repo and been training it for the talking heads face model, the outputs and tests are producing really great results throughout, however after epoch 50 it gets stuck training. I've tried using bacthsize 1 and I still get the same problem. Tried rolling back the iter.txt file to try and run from epoch 49, it still gets stuck after saving the latest model at epoch 50. Below is the command I'm using to start training it and the output its stuck on.

python train.py --name face --dataset_mode fewshot_face --adaptive_spade --warp_ref --spade_combine --loadSize 512  --batchSize 2 --continue_train --gpu_id 1,0 
CustomDatasetDataLoader
3 sequences
dataset [FaceDataset] was created
Resuming from epoch 51 at iteration 0
create web directory ./checkpoints/face/web...
---------- Networks initialized -------------
---------- Optimizers initialized -------------
update learning rate: 0.000400 -> 0.000040
---------- Now start training multiple frames -------------
Pretrained network G has fewer layers; The following are not initialized:
['flow_network_temp.conv_flow', 'flow_network_temp.conv_w', 'flow_network_temp.down_flow', 'flow_network_temp.res_flow', 'flow_network_temp.up_flow', 'img_prev_embedding.conv_first', 'img_prev_embedding.down_0', 'img_prev_embedding.down_1', 'img_prev_embedding.down_2', 'img_prev_embedding.down_3', 'img_prev_embedding.down_4', 'img_prev_embedding.up_0', 'img_prev_embedding.up_1', 'img_prev_embedding.up_2', 'img_prev_embedding.up_3', 'img_prev_embedding.up_4']
network loaded from ./checkpoints/face/latest_net_D.pth
./checkpoints/face/latest_net_DT.pth not exists yet!
model [Vid2VidModel] was created
update learning rate: 0.000040 -> 0.000039
--- Updating training sequence length to 4 ---
/home/vision/venv2/lib/python3.6/site-packages/torch/nn/functional.py:2479: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))

![Screenshot from 2020-02-19 16-46-04](https://user-images.githubusercontent.com/56768856/74845238-5dc94680-5337-11ea-824a-888ec7ef82b8.png)

I'm running on 2 RTX 2080 Ti GPUs with 11gb VRAM each...

**Comment by scarymrgrey** [comment]
Did you have a performance difference between 1x VideoCard vs 2x VideoCards?
I have no difference at all, the same performance.
2x GTX1080ti

**Comment by FredMusoro** [comment]
I haven't trained using just one GPU, I used both through out, it's only when I run the test scripts that I run on the second GPU specifically, adding the finetune argument causes the first GPU to dump the core...

Are you using the latest source?

**Comment by scarymrgrey** [comment]
Yes. The same story with the recent and previous versions. The only difference while using multiple gpu, I can double --batchSize (8 against 4). But it doesn't affect performance

**Comment by macriluke** [comment]
Try with 1 GPU- I think you've got an error that you can't see that you're hung up on. 

The model hyper parameters seem to tweak themselves as training proceeds- it reports things like adjustments to the learning rate and 'training sequence length.' I wonder if one of these automatic adjustments causes an issue- I'd have said you were running out of memory but you said you dropped the batch size already.

**Comment by FredMusoro** [comment]
1 GPU using batchsize 2 yes?

**Comment by tcwang0509** [comment]
This repo is now deprecated. Please refer to the new Imaginaire repo: https://github.com/NVlabs/imaginaire.
