### ISSUE TITLE
Unable to donwload the pretrained flownet2 weights and dataset from google drive

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [NVlabs/few-shot-vid2vid#4]
My network problem from you know why
But any other possible ways to share these files?

**Comment by jajube** [comment]
Pre-trained models are not released. 

Datasets from Google Drive should work. If not, just download it manually, adding the `file_id` to the end of this link
>https://drive.google.com/uc?export=download&id=

For datasets, current `file_id` is
https://github.com/NVlabs/few-shot-vid2vid/blob/492e3d3e438aa310f34ec5e87939deda73742855/scripts/download_datasets.py#L4

so the final link is:

>https://drive.google.com/uc?export=download&id=1NyxrzJbHgDOpf-nRJhfxsHqWNDW_D1TV

For flownet2, current `file_id` is
https://github.com/NVlabs/few-shot-vid2vid/blob/492e3d3e438aa310f34ec5e87939deda73742855/scripts/download_flownet2.py#L5

> https://drive.google.com/uc?export=download&id=1E8re-b6csNuo-abg1vJKCDjCzlIam50F

**Comment by AaronWong** [comment]
you can download in baidu pan
link: https://pan.baidu.com/s/1RSPYwwkqgOyLuP59sQRVCg 
code: uk57

**Comment by MengXinChengXuYuan** [comment]
Many thanks !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by f-rambo** [comment]
unsubscribe






在 2019-12-11 16:13:57，"MengXinChengXuYuan" <notifications@github.com> 写道：


Closed #4.
