### ISSUE TITLE
Very bad results

### ISSUE THREAD

**Issue by hamzatrq** [NVlabs/few-shot-vid2vid#42]
Getting very bad results even for the first 50 epochs. 

At 15 epochs:
![00000](https://user-images.githubusercontent.com/13986516/75623559-e1532500-5bcc-11ea-85d9-3e36ede52db7.jpg)

At 30 epochs:
![00000](https://user-images.githubusercontent.com/13986516/75623562-f039d780-5bcc-11ea-9f5b-b74593d728ba.jpg)

At 50 epochs:
![00000](https://user-images.githubusercontent.com/13986516/75623566-0051b700-5bcd-11ea-8e03-21444b51af6a.jpg)

From start my f_flow value is very high but I am not sure if it has something to do with the issue and if yes what exactly is wrong. 

Log File:
[loss_log.txt](https://github.com/NVlabs/few-shot-vid2vid/files/4271616/loss_log.txt)

**Comment by macriluke** [comment]
Have you also observed that the raw_image is sometimes a different person from the reference and target faces?

I get decent results up to 50 or so and then the model slowly degrades as it gets closer to 100 epochs.

I have noticed very bad results when the target face is angled opposite the reference face. training with --no_flip may help but I'm not sure.

My dataset is broken into frame sequences of single faces, so reference face and target face are always the same person, and the background doesn't change drastically between them. This is why it is very odd raw_image includes a face that isn't the same person as ref and target.

**Comment by FredMusoro** [comment]
It seems higher versions of pytorch have strange warping behavior, because of it the model diverges. Are you using a version of pytorch perhaps higher than 1.2.0? Fixed the problem for me...

**Comment by macriluke** [comment]
> It seems higher versions of pytorch have strange warping behavior, because of it the model diverges. Are you using a version of pytorch perhaps higher than 1.2.0? Fixed the problem for me...

As for myself, I'm using torch 1.0.0- I still get poor warps.

**Comment by tcwang0509** [comment]
This repo is now deprecated. Please refer to the new Imaginaire repo: https://github.com/NVlabs/imaginaire.
