### ISSUE TITLE
channelnorm_cuda Module import error

### ISSUE THREAD

**Issue by kartikJ-9** [NVlabs/few-shot-vid2vid#45]
I am implementing few shot vid2vid in google  colab. And I am getting this error on executing train.py
----------------------------------------------------------------------------------------------------------------- 
 File "/content/few-shot-vid2vid/models/networks/flownet2_pytorch/networks/channelnorm_package/channelnorm.py", line 3, in <module>
    import channelnorm_cuda
ModuleNotFoundError: No module named 'channelnorm_cuda'

**Comment by TongHengcheng** [comment]
You should compile flownet2
