### ISSUE TITLE
Can share the whole youtube dance dataset‘s URLs?

### ISSUE THREAD

**Issue by dypromise** [NVlabs/few-shot-vid2vid#48]
I scan the downloaded example dataset, in dance dataset, it just has 2 clips(which contains about 10 images totally), so the how can i get urls of whole youtube dance dataset to reproduce performance in paper? dear author, could you share it ? I'll appreciate it very much

**Comment by Z863058** [comment]
Thinked beauty!

**Comment by chatzikon** [comment]
what happened with this? could we have the URLs? :P
