### ISSUE TITLE
The CUDA version

### ISSUE THREAD

**Issue by xiaoyun4** [NVlabs/few-shot-vid2vid#5]
the CUDA version of my pc is 9.0

When i compile the snapshot of FlowNet2 by running python scripts/download_flownet2.py, the error is "correlation_cuda.cc:4:35: fatal error: ATen/cuda/CUDAContext.h: No such file or directory"

I think the reason is that the CUDA version does not match.

Could you please tell the CUDA version?

**Comment by jajube** [comment]
I think that's a file from pytorch. What's your pytorch version?
You can run this to check your version
```bash
python -c "import torch; print(torch.__version__)"
```

**Comment by xiaoyun4** [comment]
The pytorch version of my pc is 0.4.1.

**Comment by jajube** [comment]
CUDAContext.h was added in v1.0.

Update PyTorch to at least v1.2, which is the minimum version required, as it's written in the Prerequisites.
 I'm using the latest version (1.3.1) and it works fine

> ## Prerequisites
- Linux or macOS
- Python 3
- NVIDIA GPU + CUDA cuDNN
- ### **PyTorch 1.2**

**Comment by xiaoyun4** [comment]
OK，thanks a lot!

**Comment by f-rambo** [comment]
unsubscribe






在 2019-12-12 16:34:38，"Xiaoyun" <notifications@github.com> 写道：


Closed #5.

**Comment by f-rambo** [comment]
unsubscribe






At 2019-12-12 11:59:36, "jajube" <notifications@github.com> wrote:


CUDAContext.h was added in v1.0.

Update PyTorch to at least v1.2, which is the minimum version required, as it's written in the Prerequisites.
I'm using the latest version (1.3.1) and it works fine

Prerequisites
Linux or macOS
Python 3
NVIDIA GPU + CUDA cuDNN
PyTorch 1.2

**Comment by f-rambo** [comment]
unsubscribe.



At 2019-12-12 11:48:10, "jajube" <notifications@github.com> wrote:


I think that's a file from pytorch. What's your pytorch version?
You can run this to check your version

python -c "import torch; print(torch.__version__)"

**Comment by f-rambo** [comment]
unsubscribe.






At 2019-12-12 11:51:59, "Xiaoyun" <notifications@github.com> wrote:


The pytorch version of my pc is 0.4.1.
