### ISSUE TITLE
GPU Driver specification

### ISSUE THREAD

**Issue by kartikJ-9** [NVlabs/few-shot-vid2vid#50]
I am using Google Colab (GPU runtime) to replicate the results of the paper. Pytorch version is 1.14, CUDA v10, and Nvidia-smi driver 418.67, Numpy version 1.17. Torchvision 0.5

On executing train.py I am getting the following error : 
"CUDA driver version is insufficient for CUDA runtime version"

In google colab: usr/local/cuda is used, which is v10. So, what does CUDA runtime version imply?

**Comment by BaldrLector** [comment]
It depends on your Pytorch version, Pytorch 1.14 ask CUDA 10.1 at least, install the right version of Pytorch will fix this issue.
