### ISSUE TITLE
problem with fashion dataset

### ISSUE THREAD

**Issue by CrossLee1** [NVlabs/few-shot-vid2vid#55]
I use the newest code and fashion dataset, but got unexpected result, could someone tell me what is the problem, thanks in advance 

![image](https://user-images.githubusercontent.com/18067400/83961193-5cf6f900-a8c3-11ea-885e-0af224330efc.png)

**Comment by tcwang0509** [comment]
This repo is now deprecated. Please refer to the new Imaginaire repo: https://github.com/NVlabs/imaginaire.
