### ISSUE TITLE
Can not converge in training

### ISSUE THREAD

**Issue by hungsing92** [NVlabs/few-shot-vid2vid#57]
Hi,

   Many thanks for your excellent work!
  
  I used your scripts to preprocess my data, and followed your suggestion training command to train it. 

  Training command: 
  ```  
python  -m torch.distributed.launch --nproc_per_node=4 train.py --name pose \
    --dataset_mode fewshot_pose --adaptive_spade --warp_ref --spade_combine \
    --remove_face_labels --add_face_D --batchSize 4 --niter 100 --niter_single 100 --distributed 
  ```

  But I met some problems. First, the warped image seemed so bad:

![image](https://user-images.githubusercontent.com/27841572/84967832-8e838600-b147-11ea-942f-6bf2e018d9b4.png)

  Second, after 50 epoches(niter_single =50), the network started to train the flow network to generate videos. Howerver the flow network cannot converge and the final output changed to black:
    Nan occured:
![image](https://user-images.githubusercontent.com/27841572/84969442-4b2b1680-b14b-11ea-82f2-2456c5d7672e.png)

![image](https://user-images.githubusercontent.com/27841572/84968298-baebd200-b148-11ea-8746-26791064738a.png)

![image](https://user-images.githubusercontent.com/27841572/84968279-af001000-b148-11ea-82f9-2729ccd0fa94.png)

![image](https://user-images.githubusercontent.com/27841572/84968211-8b3cca00-b148-11ea-8c13-f074548ca517.png)

Can you give me some suggestion? Thank you very much!

**Comment by akkinenic** [comment]
Hi 
How are you pre-processing dataset using the data/preprocess?

**Comment by tcwang0509** [comment]
Sorry I think there's some problem with distributed data parallel training now. I have been able to reproduce the same results you got. I'll look into it and try to find out what's going wrong...

**Comment by Bowenwu1** [comment]
<img width="1188" alt="截屏2020-09-24 下午7 41 20" src="https://user-images.githubusercontent.com/16816766/94140585-06c3bb00-fe9e-11ea-9b00-b6f2b5d5d8df.png">

hi! any update on this issue? It seems my problem is the same

**Comment by tcwang0509** [comment]
This repo is now deprecated. Please refer to the new Imaginaire repo: https://github.com/NVlabs/imaginaire.
