### ISSUE TITLE
How to pre-process pose dataset

### ISSUE THREAD

**Issue by akkinenic** [NVlabs/few-shot-vid2vid#58]
Can someone share how to pre-process pose dataset?

**Comment by hungsing92** [comment]
Install openpose and densepose，and run preprocess.py

**Comment by Jarvisss** [comment]
I only use openpose and did not configure densepose, and here's my pre-process solution on Ubuntu 18.04:
## Install Openpose
- follow the official instruction from  [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose#installation-reinstallation-and-uninstallation)

## Run preprocess.py
`python preprocess.py 
--steps openpose,clean,divide_sequences  
--video_root /your/path/to/videos/ 
--output_root /your/path/to/output 
--openpose_root /your/path/to/openpose
`

`--openpose_root` is where your openpose is installed, under which you will find 'build/example/opepose/openpose.bin'

**Comment by Jarvisss** [comment]
> I only use Openpose and do not configure Densepose, and here's my pre-process solution on Ubuntu 18.04:
> 
> ## Install Openpose
> * follow the official instruction from  [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose#installation-reinstallation-and-uninstallation)
> 
> ## Run preprocess.py
> `python preprocess.py --steps openpose,clean,divide_sequences --video_root /your/path/to/videos/ --output_root /your/path/to/output --openpose_root /your/path/to/openpose `
> 
> `--openpose_root` is where your openpose is installed, under which you will find 'build/example/opepose/openpose.bin'

## update
I ran with `--steps openpose, clean, divide_sequence`,
but all the openpose results were deleted, as the code 
https://github.com/NVlabs/few-shot-vid2vid/blob/bc1135071c9a3b166291dfab8cc3314a50585f09/data/preprocess/preprocess.py#L64

check for densepose result, if there are no densepose result in the folder, it will delete the frame.

So some part of my pre-processed data were gone.. 

I suggest the one who wants to pre-process to install both the Densepose and Openpose, 
otherwise the code should be modified **before you do the clean step**

**Comment by guofengming11** [comment]
> > I only use Openpose and do not configure Densepose, and here's my pre-process solution on Ubuntu 18.04:
> > ## Install Openpose
> > 
> > * follow the official instruction from  [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose#installation-reinstallation-and-uninstallation)
> > 
> > ## Run preprocess.py
> > `python preprocess.py --steps openpose,clean,divide_sequences --video_root /your/path/to/videos/ --output_root /your/path/to/output --openpose_root /your/path/to/openpose `
> > `--openpose_root` is where your openpose is installed, under which you will find 'build/example/opepose/openpose.bin'
> 
> ## update
> I ran with `--steps openpose, clean, divide_sequence`,
> but all the openpose results were deleted, as the code
> https://github.com/NVlabs/few-shot-vid2vid/blob/bc1135071c9a3b166291dfab8cc3314a50585f09/data/preprocess/preprocess.py#L64
> 
> check for densepose result, if there are no densepose result in the folder, it will delete the frame.
> 
> So some part of my pre-processed data were gone..
> 
> I suggest the one who wants to pre-process to install both the Densepose and Openpose,
> otherwise the code should be modified **before you do the clean step**

Could I only use openpose ，then start training，how to start like that？
