### ISSUE TITLE
Missing initialization in data/fewshot_pose_dataset.py

### ISSUE THREAD

**Issue by GIMPS** [NVlabs/few-shot-vid2vid#59]
The latest [commit](https://github.com/NVlabs/few-shot-vid2vid/commit/3a9517aa2afb94f26c82b069c88c93fde01253d6) on data preprocessing leads to UnboundLocalError during inference. `ref_ppl_indices` and `ppl_indices` should be initialized to `None` at [data/fewshot_pose_dataset.py#L90](https://github.com/NVlabs/few-shot-vid2vid/blob/e80e7944a487470f72b718da127ebf27d2f3c258/data/fewshot_pose_dataset.py#L90). @tcwang0509 please kindly have a look.

**Comment by tcwang0509** [comment]
Thanks for pointing this out! It is fixed now.
