### ISSUE TITLE
Validation Results Are Good But Test Results Are Unsatisfactory (Pose)

### ISSUE THREAD

**Issue by erkankaracakan** [NVlabs/few-shot-vid2vid#63]
Thanks for this excellent works.

I am trying to train for pose.
My dataset has 3 sequences and nearly 40000 frames.
Train is at 99 epochs now.
Validation results are very good.
But when i take a test, results are unsatisfactory.
Hands like ghost and face is very bad.
Shall I wait or is there a problem?

Train code that i used is here.
`python train.py --name pose --dataset_mode fewshot_pose --adaptive_spade --warp_ref --spade_combine --niter_single 150 --niter 200 --batchSize 1 --lr 0.00004`

Thanks a lot.

**Comment by cszy98** [comment]
maybe "--remove_face_labels" and "--add_face_D" will be useful.

**Comment by erkankaracakan** [comment]
> maybe "--remove_face_labels" and "--add_face_D" will be useful.

I  trained until 60 epoch using them.
But faces were terrible in validation results, like the following issue.
So i have started a new train without them.
Now, validation results are good but test results not.

https://github.com/NVlabs/few-shot-vid2vid/issues/24

**Comment by deucalionAlpha** [comment]
Have you trained the face model? Have you meet the problem at this link https://github.com/NVlabs/few-shot-vid2vid/issues/64?
or can you share the face-trained model with me? thank you!

**Comment by tcwang0509** [comment]
This repo is now deprecated. Please refer to the new Imaginaire repo: https://github.com/NVlabs/imaginaire.
