### ISSUE TITLE
About train and test 

### ISSUE THREAD

**Issue by deucalionAlpha** [NVlabs/few-shot-vid2vid#64]
Apparently,The training scale is very large. I adjusted the number of epochs, hoping to train the model to be tested as soon as possible, but the following error was reported during the test. 

![image](https://user-images.githubusercontent.com/48853736/89097779-9146eb80-d414-11ea-8585-1be7961ccc12.png)

The results of the test are as follows

![image](https://user-images.githubusercontent.com/48853736/89097787-c2bfb700-d414-11ea-97cb-39fd67a68a77.png)

So,how to adjust the training model scale correctly? Or please share a model that can be tested, thank you! !

**Comment by tcwang0509** [comment]
This repo is now deprecated. Please refer to the new Imaginaire repo: https://github.com/NVlabs/imaginaire.
