### ISSUE TITLE
Can someone share the pose model with me？

### ISSUE THREAD

**Issue by zt1112** [NVlabs/few-shot-vid2vid#66]
I am a student of BUPT, and I need a pos-to-body model for research, can someone share the pose model with me?
Thanks very much! 
My Email address：441869213@qq.com

**Comment by AmberCheng** [comment]
> I am a student of BUPT, and I need a pos-to-body model for research, can someone share the pose model with me?
> Thanks very much!
> My Email address：[441869213@qq.com](mailto:441869213@qq.com)

I am not sure whether you need the flownet2 model. Hope this [issue](https://github.com/NVlabs/few-shot-vid2vid/issues/4)  helps.

**Comment by tcwang0509** [comment]
Duplicate of #22
