### ISSUE TITLE
Paired vs unpaired video translation

### ISSUE THREAD

**Issue by jlim13** [NVlabs/few-shot-vid2vid#69]
Hi, I wanted to follow up on this person's post on vid2vid. 
https://github.com/NVIDIA/vid2vid/issues/21

In the **training** subsection in section 3, you write ` Our framework is trained in the supervised setting where paired s and x
are available `. Note: I removed the sub/super scripts because it would not easily copy and paste. This means that you need paired videos, right? So if I was translating between synthetic to real, the synthetic should be the same as the real, right?

**Comment by tcwang0509** [comment]
Yes this repo is for paired video translation.
