### ISSUE TITLE
Youtube playlist 3 - Pose model

### ISSUE THREAD

**Issue by kaswani29** [NVlabs/few-shot-vid2vid#77]
Third youtube plaliyst [link](https://www.youtube.com/playlist?list=PLsVSF-hJhvBKV9XDaqJAEx-otHG1_XT9q) has more than 90% videos with multiple people in single frame will that affect the model performance or does it help model generalize ?

**Comment by tcwang0509** [comment]
Using the preprocessing code, it should crop only one person out at once.
