### ISSUE TITLE
[face]Is the training result normal?

### ISSUE THREAD

**Issue by DDDlk** [NVlabs/few-shot-vid2vid#78]
python3  train.py --name face --dataset_mode fewshot_face --adaptive_spade --warp_ref --spade_combine --batchSize 8  --dataroot   scripts/datasets/face
with cuda 9.2 pytorch1.2.0 python3.6 
![image](https://user-images.githubusercontent.com/22271047/97515018-0f427080-19cb-11eb-8cff-6092996f6cdc.png)
![image](https://user-images.githubusercontent.com/22271047/97515078-313bf300-19cb-11eb-9aa5-8b032dcfdc79.png)
![image](https://user-images.githubusercontent.com/22271047/97517568-68f96980-19d0-11eb-8401-1efd77de5d22.png)

**Comment by swpucl** [comment]
I meet the same problem.
Do you solve it?

**Comment by tcwang0509** [comment]
This repo is now deprecated. Please refer to the new Imaginaire repo: https://github.com/NVlabs/imaginaire.
