### ISSUE TITLE
GTC 2021 animated video

### ISSUE THREAD

**Issue by seekingdeep** [NVlabs/few-shot-vid2vid#83]
@tcwang0509 @mingyuliutw Hi there,
Regarding the [video animation in the GTC 2021](https://youtu.be/eAn_oiZwUXA?t=930), was it made using this repository?

https://user-images.githubusercontent.com/71519088/115122581-47615e00-9fc1-11eb-94d2-8480abce96dc.mp4

**Comment by mingyuliutw** [comment]
No,it is made by face-vid2vid.

**Comment by seekingdeep** [comment]
- It's interesting to know the details of how this animation was created.
- Will the code for face-vid2vid be released.
- Also, how what are the main differences between face-vid2vid and few-shot-vid2vid.
